config/routes.rb
UserAuth::Application.routes.draw do

  get 'orders/new'

  get 'bookings/new'

  get 'bookings/index'

  
  resources :users,:movies,:centers,:adminlogins,:admins,:feedbacks, :films,:trailers,:news
  resources :sessions
  resources :bookings
  resources :films
  resources :pages
  resources :orders
  root :to => 'sessions#login'
  

  match "/signup", :to => "users#new", :via => [:get]
  match "/login", :to => "sessions#login", :via => [:get]
  match "/logout", :to => "sessions#logout", :via => [:get]
  match "/home", :to => "pages#home", :via => [:get]
  match "/profile", :to => "sessions#profile", :via => [:get]
  match "/setting", :to => "sessions#setting", :via => [:get]
  match "/login_attempt", to: "sessions#login_attempt", :via => [:post]
  match '/sample', to: 'bookings#sample', :via => [:get]
  match "/movienews", :to => "pages#news", :via => [:get]
  match "/movie_trailer", :to => "pages#trailer", :via => [:get]
  match "/admin_profile", :to => "adminlogin#admin_profile", :via => [:get]
  match "/admin_login", :to => "adminlogins#login", :via => [:get]
  match "/admin_logout", :to => "adminlogins#logout", :via => [:get]
  match "/feedback_rating", :to => "pages#feedback", :via => [:get]
  match "/aboutus", :to => "pages#aboutus", :via => [:get]
  match "/contact", :to => "pages#contact", :via => [:get]
  match "/film_details", :to => "pages#film", :via => [:get]
  match "/admin_login_attempt", to: "adminlogins#admin_login_attempt", :via => [:post]
  get 'bookings/update_cities', as: 'update_cities'
  get 'bookings/show'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	attr_accessor :password

    attr_accessible :username, :email, :password, :password_confirmation,:gender

    EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password,:in => 6..20, :on => :create
    
    before_save :encrypt_password

    def self.authenticate(username_or_email, login_password)
        if EMAIL_REGEX.match(username_or_email)
            admin = Admin.find_by_email(username_or_email)
        else
            admin = Admin.find_by_username(username_or_email)
        end

        if admin && admin.match_password(login_password)
            return admin
        end
    end

    def match_password(login_password)
        encrypted_password == encrypt(login_password)
    end

    private

    def encrypt_password
        if password.present?
            self.salt = make_salt(password) if self.new_record?
            self.encrypted_password = encrypt(password)
        end
    end

    def encrypt(string)
        secure_hash("#{salt}#{string}")
    end

    def make_salt(string)
        secure_hash("#{Date.today}#{string}")
        
    end

    def secure_hash(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	attr_accessible :movie_id, :center_id, :date, :time,:no_tickets
	validates :movie_id, :presence => "true"
	validates :center_id, :presence => "true"
	validates :date, :presence => "true"
	validates :time, :presence => "true"
	validates :no_tickets, :presence => "true"
end

app/models/center.rb
class Center < ActiveRecord::Base
	 belongs_to :movie
  has_many :booking
  attr_accessible :name, :movie_id
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	attr_accessible :movie_name,:user_name, :rating, :comment
	
end

app/models/film.rb
class Film < ActiveRecord::Base
	attr_accessible :name, :actors, :description, :director
 	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Film.all
  		end
	end 
 
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	 has_many :centers
  	 has_many :booking
  	 attr_accessible :name
  	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Movie.all
  		end
	end
end

app/models/news.rb
class News < ActiveRecord::Base
	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		News.all
  		end
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Trailer.all
  		end
	end
end

app/models/user.rb
 class User < ActiveRecord::Base

    attr_accessor :password

    attr_accessible :username, :email, :password, :password_confirmation,:gender

    EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password,:in => 6..20, :on => :create
    
    before_save :encrypt_password

    def self.authenticate(username_or_email, login_password)
        if EMAIL_REGEX.match(username_or_email)
            user = User.find_by_email(username_or_email)
        else
            user = User.find_by_username(username_or_email)
        end

        if user && user.match_password(login_password)
            return user
        end
    end

    def match_password(login_password)
        encrypted_password == encrypt(login_password)
    end

    private

    def encrypt_password
        if password.present?
            self.salt = make_salt(password) if self.new_record?
            self.encrypted_password = encrypt(password)
        end
    end

    def encrypt(string)
        secure_hash("#{salt}#{string}")
    end

    def make_salt(string)
        secure_hash("#{Date.today}#{string}")
        
    end

    def secure_hash(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/edit.html.erb
<% @page_title = "Update" %>
<div class="Sign_Form">
  <h1>Update Profile </h1>
  <% if @admin.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @admin.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
  <table align="center">
  <%= form_for(@admin) do |f| %>
   <tr><td> <%= f.text_field :username,:class => "textox",:placeholder =>"admin name "%> </td></tr>
     <tr><td><%= f.text_field :email,:class => "textox",:placeholder =>" Email"%></td></tr>
     <tr><td><%= f.password_field :password,:class => "textox",:placeholder =>"Password"%></td></tr>
    <tr><td><%= f.password_field :password_confirmation,:class => "textox",:placeholder =>"password_confirmation"%></td></tr>
    <tr><td> <label class="button"><%= f.radio_button :gender, "Female", :checked => (:gender == 'female')? true:false %><span class="outer"><span class="inner"></span></span>Female </label> 
     <label class="button"><%=f.radio_button :gender, "Male", :checked => (:gender == 'male')? true:false %><span class="outer"><span class="inner"></span></span>Male </label> </td></tr>
    <tr><td><%= f.submit "Update",:class =>"css_button" %>
    </td><tr>
  </table>
  <% end %>
</div>


app/views/admins/new.html.erb
<% @page_title = "AdminAuth | Admin Signup" %>
<center>
  <h2 align="center">Admin Sign Up</h2>
  <% if @admin.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @admin.errors.full_messages %>
      <li><%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
  <table >
  <%= form_for(@admin) do |f| %>
   <tr><td> <%= f.text_field :username,:class => "textox",:placeholder =>"User name "%> </td></tr>
     <tr><td><%= f.text_field :email,:class => "textox",:placeholder =>" Email"%></td></tr>
     <tr><td><%= f.password_field :password,:class => "textox",:placeholder =>"Password"%></td></tr>
    <tr><td><%= f.password_field :password_confirmation,:class => "textox",:placeholder =>"password_confirmation"%></td></tr>
    <tr><td> <label class="button"><%= f.radio_button :gender, "Female", :checked => (:gender == 'female')? true:false %><span class="outer"><span class="inner"></span></span>Female </label> 
     <label class="button"><%=f.radio_button :gender, "Male", :checked => (:gender == 'male')? true:false %><span class="outer"><span class="inner"></span></span>Male </label> </td></tr>
    <tr><td><%= f.submit "create",:class =>"css_button" %>
    <%= link_to "Admin Login" ,:class => "css_button" %></td><tr>
  </table>
  <% end %>
  <center>

app/views/admins/show.html.erb
<h2 align="center"><%= @current_admin.username%>'s Profile </h2> 
<center>
<table class ="boldtable" align="center" style="width:50%"  border="1" cellspacing="0" cellpadding="3" style="font-size: 8px">

    <tr>
    <td>admin Name</td>
    <td><%= @current_admin.username%></td>   
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @current_admin.email%></td>    
     </tr>
     <td>Gender</td>
    <td><%= @current_admin.gender%></td>    
     </tr>
  
</table> 
<button class="css_button" ><%= link_to "Update", edit_admin_path(@current_admin)  %></button>
     <button class="css_button" ><%= link_to "back", home_path %></button></center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= stylesheet_link_tag "style" %>
   <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "rails.jquery.js","application" %>
   <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
  <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
  <%= javascript_include_tag :defaults %>
  

 

    <%= csrf_meta_tags %>
    
  
</head>
<body>
<div class="blended_grid">
	<div id="header">
    <h1>
    <%=link_to "Online Movie Tickets" ,home_path%>
   </h1>

        <h3 align="right"> <%if  session[:user_id].nil? and session[:admin_id].nil?%>  
            
             <%=link_to "Register", signup_path %>&nbsp&nbsp
             <%=link_to "Login", login_path %>&nbsp&nbsp&nbsp&nbsp
             <%=link_to "Admin signin", admin_login_path %>
             <%elsif session[:user_id].nil? %>
             Admin Account &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                Login as :<%= session[:admin_email] %>&nbsp&nbsp&nbsp
              <%=link_to "Log Out" ,admin_logout_path %> 
              <ul id="nav" >
      <%@current_admin = Admin.find(session[:admin_id])%>
      <li><%= link_to "Profile",admin_path(@current_admin)%></li>
      <li><%= link_to "Add movies",new_movie_path%></li>
      <li><%= link_to "Add centers",new_center_path%></li>
      
   </ul>
           <%else%>
                Login as :<%= session[:user_email] %>&nbsp&nbsp&nbsp
              <%=link_to "Log Out" ,logout_path %> 
              <ul id="nav" >
      <%@current_user = User.find(session[:user_id])%>
      <%session[:user_name]=@current_user.username%>
      <li><%= link_to "Profile",user_path(@current_user)%></li>
      <li><%= link_to "Book Tickets",new_booking_path  %></li>
      <li><%= link_to "news",movienews_path  %></li>
      <li><%= link_to "Film Details ",film_details_path %></li>
      <li><%= link_to "Trailers",movie_trailer_path  %></li>
       <li><%= link_to "Feedback",feedback_rating_path %></li>
   </ul>

            <%end%></br>
            <%= notice %>
            <%= alert %>
  
        </h3>
        </div>

    
      <div id="navg"></br>
        <div id="menu8"> 
               <ul >
      <li><%= link_to "Home",home_path %></li>
     <li><%= link_to "News",movienews_path  %></li>
     <li><%= link_to "Trailers",movie_trailer_path  %></li>
    
      <li><%= link_to "About us", aboutus_path %></li>
      <li><%= link_to "Contact us",contact_path%></li>
      
   </ul>
 </div>
      </div>
    
<div id="section">
  <%= yield %>
</div>
<div id="footer">
Copyright © Online Movies
</div>
</div>
</body>
</html>