config/routes.rb
UserAuth::Application.routes.draw do

  get 'orders/new'

  get 'bookings/new'

  get 'bookings/index'

  
  resources :users,:movies,:centers,:adminlogins,:admins,:feedbacks, :films,:trailers,:news
  resources :sessions
  resources :bookings
  resources :films
  resources :pages
  resources :orders
  root :to => 'sessions#login'
  

  match "/signup", :to => "users#new", :via => [:get]
  match "/login", :to => "sessions#login", :via => [:get]
  match "/logout", :to => "sessions#logout", :via => [:get]
  match "/home", :to => "pages#home", :via => [:get]
  match "/profile", :to => "sessions#profile", :via => [:get]
  match "/setting", :to => "sessions#setting", :via => [:get]
  match "/login_attempt", to: "sessions#login_attempt", :via => [:post]
  match '/sample', to: 'bookings#sample', :via => [:get]
  match "/movienews", :to => "pages#news", :via => [:get]
  match "/movie_trailer", :to => "pages#trailer", :via => [:get]
  match "/admin_profile", :to => "adminlogin#admin_profile", :via => [:get]
  match "/admin_login", :to => "adminlogins#login", :via => [:get]
  match "/admin_logout", :to => "adminlogins#logout", :via => [:get]
  match "/feedback_rating", :to => "pages#feedback", :via => [:get]
  match "/aboutus", :to => "pages#aboutus", :via => [:get]
  match "/contact", :to => "pages#contact", :via => [:get]
  match "/film_details", :to => "pages#film", :via => [:get]
  match "/admin_login_attempt", to: "adminlogins#admin_login_attempt", :via => [:post]
  get 'bookings/update_cities', as: 'update_cities'
  get 'bookings/show'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	attr_accessor :password

    attr_accessible :username, :email, :password, :password_confirmation,:gender

    EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password,:in => 6..20, :on => :create
    
    before_save :encrypt_password

    def self.authenticate(username_or_email, login_password)
        if EMAIL_REGEX.match(username_or_email)
            admin = Admin.find_by_email(username_or_email)
        else
            admin = Admin.find_by_username(username_or_email)
        end

        if admin && admin.match_password(login_password)
            return admin
        end
    end

    def match_password(login_password)
        encrypted_password == encrypt(login_password)
    end

    private

    def encrypt_password
        if password.present?
            self.salt = make_salt(password) if self.new_record?
            self.encrypted_password = encrypt(password)
        end
    end

    def encrypt(string)
        secure_hash("#{salt}#{string}")
    end

    def make_salt(string)
        secure_hash("#{Date.today}#{string}")
        
    end

    def secure_hash(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	attr_accessible :movie_id, :center_id, :date, :time,:no_tickets
	validates :movie_id, :presence => "true"
	validates :center_id, :presence => "true"
	validates :date, :presence => "true"
	validates :time, :presence => "true"
	validates :no_tickets, :presence => "true"
end

app/models/center.rb
class Center < ActiveRecord::Base
	 belongs_to :movie
  has_many :booking
  attr_accessible :name, :movie_id
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	attr_accessible :movie_name,:user_name, :rating, :comment
	
end

app/models/film.rb
class Film < ActiveRecord::Base
	attr_accessible :name, :actors, :description, :director
 	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Film.all
  		end
	end 
 
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	 has_many :centers
  	 has_many :booking
  	 attr_accessible :name
  	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Movie.all
  		end
	end
end

app/models/news.rb
class News < ActiveRecord::Base
	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		News.all
  		end
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Trailer.all
  		end
	end
end

app/models/user.rb
 class User < ActiveRecord::Base

    attr_accessor :password

    attr_accessible :username, :email, :password, :password_confirmation,:gender

    EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password,:in => 6..20, :on => :create
    
    before_save :encrypt_password

    def self.authenticate(username_or_email, login_password)
        if EMAIL_REGEX.match(username_or_email)
            user = User.find_by_email(username_or_email)
        else
            user = User.find_by_username(username_or_email)
        end

        if user && user.match_password(login_password)
            return user
        end
    end

    def match_password(login_password)
        encrypted_password == encrypt(login_password)
    end

    private

    def encrypt_password
        if password.present?
            self.salt = make_salt(password) if self.new_record?
            self.encrypted_password = encrypt(password)
        end
    end

    def encrypt(string)
        secure_hash("#{salt}#{string}")
    end

    def make_salt(string)
        secure_hash("#{Date.today}#{string}")
        
    end

    def secure_hash(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
	def new
      @center = Center.new     
  end

  def show
     @current_center = Center.find(params[:id])
  end

   def create
    	@center = Center.create(params[:center])
      # raise @center.inspect
    	if @center.save
        session[:center_id] =@center.id
        
    		flash[:notice] = "Entered center  successfully"
        flash[:color]= "valid"


        redirect_to new_center_path
      else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        render 'new'
      end
      
    end

    def edit
      @center = Center.find(params[:id])
    end

    def update
      @center = Center.find(params[:id])
      # raise @center.inspect
      if @center.update_attributes(params[:center])
        session[:center_id]=@center.id
        @current_center=Center.find(session[:center_id])
        flash[:notice] = "Updated  successfully"
        flash[:color]= "valid"
        redirect_to new_center_path
      else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        render 'edit'
      end
      
    end
    def destroy
      @center = Center.find(params[:id])
      @center.destroy
      redirect_to new_center_path
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/centers/_center.html.erb
<option value="<%= center.id %>"><%= center.name.titleize %></option>

app/views/centers/edit.html.erb
<% @page_title = "centerAuth | Signup" %>
<center>
  <h2 align="center">Adding centers for movies</h2>
  <% if @center.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @center.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
 
  
  
  <%= form_for(@center) do |f| %>
   <tr><td> <%= f.text_field :movie_id,:class => "textox",:placeholder =>"Enter movie Id "%> </td></tr>
     <tr><td><%= f.text_field :name,:class => "textox",:placeholder =>"Enter center name"%></td></tr>
    
    <tr><td><%= f.submit "edit",:class =>"css_button" %>
    </td><tr>
  </table>
  <% end %>
  </center>

app/views/centers/new.html.erb
<% @page_title = "centerAuth | Signup" %>

  <h2>Adding centers for movies</h2>
  <% if @center.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @center.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
    <table align="left">
  <%= form_for(@center) do |f| %>
   <tr><td> <%= f.text_field :movie_id,:class => "textox",:size=>"10",:placeholder =>"Enter movie Id "%> </td></tr>
     <tr><td><%= f.text_field :name,:class => "textox",:size=>"12",:placeholder =>"Enter center name"%></td></tr>
    
    <tr><td><%= f.submit "Add Center",:class =>"css_button" %></td>
     <tr><td><%=link_to "Want to add movies",new_movie_path%><td>
    </td><tr>
  </table>
   

  <%@all=Movie.all%>
  <table align="center"border='1'>
    <tr><th>Movie Id</th>
      <th colspan="3">Movie Name </th>
      <th>Movie Centers</th>

  <%for @a in @all %>
  <tr>
  <td><%=@a.id%></td>
  <td><%=@a.name%></td>
  <td><%=link_to "✎",edit_movie_path(@a)%></td>
  <td><%=link_to "✗ ",@a, method: :delete, data: { confirm: 'Are you sure？' } %></td>
  <%@centers_name=Center.where(:movie_id => @a.id)%>
  <td border="1">
  <%for @b in @centers_name %>
  <%=@b.name%>
  <%=link_to "✎",edit_center_path(@b)%>
  <%=link_to "✗ ",@b, method: :delete, data: { confirm: 'Are you sure？' }%>,
  <%end%>
  </td>
</tr>
  <%end%>
  </table >



 
  <% end %>

app/views/centers/show.html.erb
<h2 align="center"><%= @current_user.username%>'s Profile </h2> 
<center>
<table class ="boldtable" align="center" style="width:50%"  border="1" cellspacing="0" cellpadding="3" style="font-size: 8px">

    <tr>
    <td>User Name</td>
    <td><%= @current_user.username%></td>   
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @current_user.email%></td>    
     </tr>
     <td>Gender</td>
    <td><%= @current_user.gender%></td>    
     </tr>
  
</table> 
<button class="css_button" ><%= link_to "Update", edit_user_path(@current_user)  %></button>
     <button class="css_button" ><%= link_to "back", home_path %></button></center>