config/routes.rb
UserAuth::Application.routes.draw do

  get 'orders/new'

  get 'bookings/new'

  get 'bookings/index'

  
  resources :users,:movies,:centers,:adminlogins,:admins,:feedbacks, :films,:trailers,:news
  resources :sessions
  resources :bookings
  resources :films
  resources :pages
  resources :orders
  root :to => 'sessions#login'
  

  match "/signup", :to => "users#new", :via => [:get]
  match "/login", :to => "sessions#login", :via => [:get]
  match "/logout", :to => "sessions#logout", :via => [:get]
  match "/home", :to => "pages#home", :via => [:get]
  match "/profile", :to => "sessions#profile", :via => [:get]
  match "/setting", :to => "sessions#setting", :via => [:get]
  match "/login_attempt", to: "sessions#login_attempt", :via => [:post]
  match '/sample', to: 'bookings#sample', :via => [:get]
  match "/movienews", :to => "pages#news", :via => [:get]
  match "/movie_trailer", :to => "pages#trailer", :via => [:get]
  match "/admin_profile", :to => "adminlogin#admin_profile", :via => [:get]
  match "/admin_login", :to => "adminlogins#login", :via => [:get]
  match "/admin_logout", :to => "adminlogins#logout", :via => [:get]
  match "/feedback_rating", :to => "pages#feedback", :via => [:get]
  match "/aboutus", :to => "pages#aboutus", :via => [:get]
  match "/contact", :to => "pages#contact", :via => [:get]
  match "/film_details", :to => "pages#film", :via => [:get]
  match "/admin_login_attempt", to: "adminlogins#admin_login_attempt", :via => [:post]
  get 'bookings/update_cities', as: 'update_cities'
  get 'bookings/show'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	attr_accessor :password

    attr_accessible :username, :email, :password, :password_confirmation,:gender

    EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password,:in => 6..20, :on => :create
    
    before_save :encrypt_password

    def self.authenticate(username_or_email, login_password)
        if EMAIL_REGEX.match(username_or_email)
            admin = Admin.find_by_email(username_or_email)
        else
            admin = Admin.find_by_username(username_or_email)
        end

        if admin && admin.match_password(login_password)
            return admin
        end
    end

    def match_password(login_password)
        encrypted_password == encrypt(login_password)
    end

    private

    def encrypt_password
        if password.present?
            self.salt = make_salt(password) if self.new_record?
            self.encrypted_password = encrypt(password)
        end
    end

    def encrypt(string)
        secure_hash("#{salt}#{string}")
    end

    def make_salt(string)
        secure_hash("#{Date.today}#{string}")
        
    end

    def secure_hash(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	attr_accessible :movie_id, :center_id, :date, :time,:no_tickets
	validates :movie_id, :presence => "true"
	validates :center_id, :presence => "true"
	validates :date, :presence => "true"
	validates :time, :presence => "true"
	validates :no_tickets, :presence => "true"
end

app/models/center.rb
class Center < ActiveRecord::Base
	 belongs_to :movie
  has_many :booking
  attr_accessible :name, :movie_id
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	attr_accessible :movie_name,:user_name, :rating, :comment
	
end

app/models/film.rb
class Film < ActiveRecord::Base
	attr_accessible :name, :actors, :description, :director
 	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Film.all
  		end
	end 
 
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	 has_many :centers
  	 has_many :booking
  	 attr_accessible :name
  	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Movie.all
  		end
	end
end

app/models/news.rb
class News < ActiveRecord::Base
	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		News.all
  		end
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Trailer.all
  		end
	end
end

app/models/user.rb
 class User < ActiveRecord::Base

    attr_accessor :password

    attr_accessible :username, :email, :password, :password_confirmation,:gender

    EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password,:in => 6..20, :on => :create
    
    before_save :encrypt_password

    def self.authenticate(username_or_email, login_password)
        if EMAIL_REGEX.match(username_or_email)
            user = User.find_by_email(username_or_email)
        else
            user = User.find_by_username(username_or_email)
        end

        if user && user.match_password(login_password)
            return user
        end
    end

    def match_password(login_password)
        encrypted_password == encrypt(login_password)
    end

    private

    def encrypt_password
        if password.present?
            self.salt = make_salt(password) if self.new_record?
            self.encrypted_password = encrypt(password)
        end
    end

    def encrypt(string)
        secure_hash("#{salt}#{string}")
    end

    def make_salt(string)
        secure_hash("#{Date.today}#{string}")
        
    end

    def secure_hash(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	def index
      @films = Film.search params[:search]
  end
  def new


      @film = Film.new    

  end

  def show
     @film = Film.all
  end

   def create

    	@film = Film.create(params[:film])
      # raise @film.inspect
    	if @film.save
        session[:film_id] =@film.id
        
    		flash[:notice] = "Entered film  successfully"
        flash[:color]= "valid"


        redirect_to new_film_path
      else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        render 'new'
      end
      
    end

    def edit
      @film = Film.find(params[:id])
    end

    def update
      @film = Film.find(params[:id])
      # raise @film.inspect
      if @film.update_attributes(params[:film])
        session[:film_id]=@film.id
        @current_film=Film.find(session[:film_id])
        flash[:notice] = "Updated  successfully"
        flash[:color]= "valid"
        redirect_to new_film_path
      else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        render 'edit'
      end
      
    end
    def destroy
      @film = Film.find(params[:id])
      @film.destroy
      redirect_to new_film_path
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%=@film.errors.count %></h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name ,'Movie' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :director, 'director' %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :actors, 'actors' %><br />
    <%= f.text_field :actors %>
  </div>
 
  <div class="field">
    <%= f.label :description, 'description' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>

<%= link_to 'film', @film %> |
<%= link_to 'films path, films_path %>

app/views/films/index.html.erb
<h1>Film Details</h1><br/>
<%= form_tag films_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search],:class => "textox",:size =>'10' %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<%for @film in @films%>
<center><%= image_tag @film.name.delete(' ')+'1.jpg' %></center>
<p>
  <b>Movie Name :</b>

  <%= @film.name %>
</p>

<p>
  <b>Director :</b>
  <%= @film.director %>
</p>
<p>
  <b>Actors :</b>
  <%= @film.actors %>
</p>

<p>
  <b>Description :</b>
  <%= @film.description %>
</p>
<br><br><br><br>
<%end%>
<%unless @films[0]%>
<b>No result Found</b>
<%end%>

app/views/films/new.html.erb
<h1>new</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<style type="text/css" media="screen">
b {
  font-size: 1.5em;
}
  
</style>
<%@films=Film.all%>

<h1>Film Details</h1><br/>
<%for @film in @films%>
<p>
  <b>Movie Name</b>
  <%= @film.name %>
</p>

<p>
  <b>Director</b>
  <%= @film.director %>
</p>
<p>
  <b>Actors</b>
  <%= @film.actors %>
</p>

<p>
  <b>Description</b>
  <%= @film.description %>
</p>
<%end%>