config/routes.rb
UserAuth::Application.routes.draw do

  get 'orders/new'

  get 'bookings/new'

  get 'bookings/index'

  
  resources :users,:movies,:centers,:adminlogins,:admins,:feedbacks, :films,:trailers,:news
  resources :sessions
  resources :bookings
  resources :films
  resources :pages
  resources :orders
  root :to => 'sessions#login'
  

  match "/signup", :to => "users#new", :via => [:get]
  match "/login", :to => "sessions#login", :via => [:get]
  match "/logout", :to => "sessions#logout", :via => [:get]
  match "/home", :to => "pages#home", :via => [:get]
  match "/profile", :to => "sessions#profile", :via => [:get]
  match "/setting", :to => "sessions#setting", :via => [:get]
  match "/login_attempt", to: "sessions#login_attempt", :via => [:post]
  match '/sample', to: 'bookings#sample', :via => [:get]
  match "/movienews", :to => "pages#news", :via => [:get]
  match "/movie_trailer", :to => "pages#trailer", :via => [:get]
  match "/admin_profile", :to => "adminlogin#admin_profile", :via => [:get]
  match "/admin_login", :to => "adminlogins#login", :via => [:get]
  match "/admin_logout", :to => "adminlogins#logout", :via => [:get]
  match "/feedback_rating", :to => "pages#feedback", :via => [:get]
  match "/aboutus", :to => "pages#aboutus", :via => [:get]
  match "/contact", :to => "pages#contact", :via => [:get]
  match "/film_details", :to => "pages#film", :via => [:get]
  match "/admin_login_attempt", to: "adminlogins#admin_login_attempt", :via => [:post]
  get 'bookings/update_cities', as: 'update_cities'
  get 'bookings/show'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	attr_accessor :password

    attr_accessible :username, :email, :password, :password_confirmation,:gender

    EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password,:in => 6..20, :on => :create
    
    before_save :encrypt_password

    def self.authenticate(username_or_email, login_password)
        if EMAIL_REGEX.match(username_or_email)
            admin = Admin.find_by_email(username_or_email)
        else
            admin = Admin.find_by_username(username_or_email)
        end

        if admin && admin.match_password(login_password)
            return admin
        end
    end

    def match_password(login_password)
        encrypted_password == encrypt(login_password)
    end

    private

    def encrypt_password
        if password.present?
            self.salt = make_salt(password) if self.new_record?
            self.encrypted_password = encrypt(password)
        end
    end

    def encrypt(string)
        secure_hash("#{salt}#{string}")
    end

    def make_salt(string)
        secure_hash("#{Date.today}#{string}")
        
    end

    def secure_hash(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	attr_accessible :movie_id, :center_id, :date, :time,:no_tickets
	validates :movie_id, :presence => "true"
	validates :center_id, :presence => "true"
	validates :date, :presence => "true"
	validates :time, :presence => "true"
	validates :no_tickets, :presence => "true"
end

app/models/center.rb
class Center < ActiveRecord::Base
	 belongs_to :movie
  has_many :booking
  attr_accessible :name, :movie_id
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	attr_accessible :movie_name,:user_name, :rating, :comment
	
end

app/models/film.rb
class Film < ActiveRecord::Base
	attr_accessible :name, :actors, :description, :director
 	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Film.all
  		end
	end 
 
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	 has_many :centers
  	 has_many :booking
  	 attr_accessible :name
  	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Movie.all
  		end
	end
end

app/models/news.rb
class News < ActiveRecord::Base
	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		News.all
  		end
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
	def self.search(search)
  		if search
  			where(['name LIKE ?', "%#{search}%"])
  		else
    		Trailer.all
  		end
	end
end

app/models/user.rb
 class User < ActiveRecord::Base

    attr_accessor :password

    attr_accessible :username, :email, :password, :password_confirmation,:gender

    EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password,:in => 6..20, :on => :create
    
    before_save :encrypt_password

    def self.authenticate(username_or_email, login_password)
        if EMAIL_REGEX.match(username_or_email)
            user = User.find_by_email(username_or_email)
        else
            user = User.find_by_username(username_or_email)
        end

        if user && user.match_password(login_password)
            return user
        end
    end

    def match_password(login_password)
        encrypted_password == encrypt(login_password)
    end

    private

    def encrypt_password
        if password.present?
            self.salt = make_salt(password) if self.new_record?
            self.encrypted_password = encrypt(password)
        end
    end

    def encrypt(string)
        secure_hash("#{salt}#{string}")
    end

    def make_salt(string)
        secure_hash("#{Date.today}#{string}")
        
    end

    def secure_hash(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_filter :authenticate_user
  def index
      @movies = Movie.search params[:search]
    end
	def new
		@feedback = Feedback.new  
	end
	def show
     @current_feedback = Feedback.find(params[:id])
  	end

   def create

    	@feedback= Feedback.create(params[:feedback])
     
    	if @feedback.save
        session[:feedback_id] =@feedback.id
        
    		flash[:notice] = "Entered feedback  successfully"
        flash[:color]= "valid"


        redirect_to new_feedback_path(:name  =>@feedback.movie_name)
      else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        render 'new'
      end
      
    end

    def edit
      @feedback= Feedback.find(params[:id])
    end

    def update
       @feedback = Feedback.find(params[:id])
      # raise @feedback.inspect
      if @feedback.update_attributes(params[:feedback])
        session[:feedback_id]=@feedback.id
        @current_feedback=Feedback.find(session[:feedback_id])
        flash[:notice] = "Updated  successfully"
        flash[:color]= "valid"
        redirect_to new_feedback_path(:name =>@feedback.movie_name)
      else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        render 'edit'
      end
      
    end
    def destroy
      @feedback = Feedback.find(params[:id])
      @feedback.destroy
      redirect_to new_feedback_path(:name =>session[:movie_name])
    end
    def search
      @movies = Movie.search params[:search]
    end
 
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feedbacks/edit.html.erb
<% @page_title = "Feedback" %>


  <h2>Feedback</h2>
  
  <table align="center">
  <%= form_for(@feedback) do |f| %>
   <tr><td> MOVIE :</td><td><%=session[:movie_name]%><%=f.hidden_field  :movie_name,:value =>session[:movie_name]%>
    <%=f.hidden_field :user_name,:value =>session[:user_name]%></td></tr>
   <tr><td> Rating</td><td>
    <section class="container">
     <%= f.radio_button :rating,"1",:value => "1" %>
     <%= f.radio_button :rating,"2",:value => "2" %>
     <%= f.radio_button :rating,"3",:value => "3" %>
     <%= f.radio_button :rating,"4",:value => "4" %>
     <%= f.radio_button :rating,"5",:value => "5" %>
    
       
    </section><td></tr>
    <tr><td>Comment : </td><td><%=f.text_area :comment,:cols => "70", :rows => "5" %></td></tr>
    <tr><td><%= f.submit "submit",:class =>"css_button" %></td>
       <td> <%=link_to "Back",feedback_rating_path%>
        
    </td></tr>
  <tr><tr><tr><tr><tr><tr><tr><tr>
  <% end %>

</table>
  




  <script>
   $(function(){
            $('.container').rating();
        });
;(function($){
    $.fn.rating = function(callback){
        
        callback = callback || function(){};

        // each for all item
        this.each(function(i, v){
            
            $(v).data('rating', {callback:callback})
                .bind('init.rating', $.fn.rating.init)
                .bind('set.rating', $.fn.rating.set)
                .bind('hover.rating', $.fn.rating.hover)
                .trigger('init.rating');
        });
    };
    
    $.extend($.fn.rating, {
        init: function(e){
            var el = $(this),
                list = '',
                isChecked = null,
                childs = el.children(),
                i = 0,
                l = childs.length;
            
            for (; i < l; i++) {
                list = list + '<a class="star" title="' + $(childs[i]).val() + '" />';
                if ($(childs[i]).is(':checked')) {
                    isChecked = $(childs[i]).val();
                };
            };
            
            childs.hide();
            
            el
                .append('<div class="stars">' + list + '</div>')
                .trigger('set.rating', isChecked);
            
            $('a', el).bind('click', $.fn.rating.click);            
            el.trigger('hover.rating');
        },
        set: function(e, val) {
            var el = $(this),
                item = $('a', el),
                input = undefined;
            
            if (val) {
                item.removeClass('fullStar');
                
                input = item.filter(function(i){
                    if ($(this).attr('title') == val)
                        return $(this);
                    else
                        return false;
                });
                
                input
                    .addClass('fullStar')
                    .prevAll()
                    .addClass('fullStar');
            }
            
            return;
        },
        hover: function(e){
            var el = $(this),
                stars = $('a', el);
            
            stars.bind('mouseenter', function(e){
                // add tmp class when mouse enter
                $(this)
                    .addClass('tmp_fs')
                    .prevAll()
                    .addClass('tmp_fs');
                
                $(this).nextAll()
                    .addClass('tmp_es');
            });
            
            stars.bind('mouseleave', function(e){
                // remove all tmp class when mouse leave
                $(this)
                    .removeClass('tmp_fs')
                    .prevAll()
                    .removeClass('tmp_fs');
                
                $(this).nextAll()
                    .removeClass('tmp_es');
            });
        },
        click: function(e){
            e.preventDefault();
            var el = $(e.target),
                container = el.parent().parent(),
                inputs = container.children('input'),
                rate = el.attr('title');
                
            matchInput = inputs.filter(function(i){
                if ($(this).val() == rate)
                    return true;
                else
                    return false;
            });
            
            matchInput.attr('checked', true);
            
            container
                .trigger('set.rating', matchInput.val())
                .data('rating').callback(rate, e);
        }
    });
    
})(jQuery);

  </script>







app/views/feedbacks/index.html.erb

<h2>Feedback</h2>
 <%= form_tag feedbacks_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search],:class => "textox" ,:size =>'10'%>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%for @a in @movies%>
	<% @name=@a.name %>
	
	<h3 align='center'>
		<%=link_to @name,new_feedback_path(:name =>@name)%><br>
		<%=link_to image_tag(@name.delete(' ')+'1.jpg') ,new_feedback_path(:name =>@name)%></h3>
		<br><br>
<%end%>
<%unless @movies[0]%>
<b>No result Found</b>
<%end%>

app/views/feedbacks/new.html.erb
<% @page_title = "Feedback" %>
<%session[:movie_name]=params[:name]%>

  <h2>Feedback</h2>
  
  <table align="center">
  <%= form_for(@feedback) do |f| %>
   <tr><td> MOVIE :</td><td><%=session[:movie_name]%><%=f.hidden_field  :movie_name,:value =>session[:movie_name]%>
    <%=f.hidden_field :user_name,:value =>session[:user_name]%></td></tr>
   <tr><td> Rating</td><td>
    <section class="container">
     <%= f.radio_button :rating,"1",:value => "1" %>
     <%= f.radio_button :rating,"2",:value => "2" %>
     <%= f.radio_button :rating,"3",:value => "3" %>
     <%= f.radio_button :rating,"4",:value => "4" %>
     <%= f.radio_button :rating,"5",:value => "5" %>
    
       
    </section><td></tr>
    <tr><td>Comment : </td><td><%=f.text_area :comment,:cols => "70", :rows => "5" %></td></tr>
    <tr><td><%= f.submit "submit",:class =>"css_button" %></td>
       <td> <%=link_to "Back",feedback_rating_path%>
        
    </td></tr>
  <tr><tr><tr><tr><tr><tr><tr><tr>
  <% end %>


  <%@all=Feedback.where(:movie_name =>session[:movie_name]).reverse%>
  
   

  <%for@a in @all %>
  <tr>
   <td><b><%=@a.user_name%></b><td>
   </tr>
   <tr>

    <td><%"#{@a.rating}".to_i.times do %>
   
    <%= content_tag :div, class: "fullStar",align:"center" do %>
    <% end %>
    <%end%></td>
    </tr><tr>
    <td colspan="2"><%=@a.comment%>

    <%if session[:user_name]==@a.user_name%>
  <%=link_to "✎",edit_feedback_path(@a)%>
  <%=link_to "✗ ",@a, :method=> :delete, data: { confirm: 'Are you sure？' } %>
  </td><td></td>
    <%end%>
    </tr><tr><tr><tr><tr><tr><tr><tr><tr><tr><tr>
  <%end%>
</table>
  




  <script>
   $(function(){
            $('.container').rating();
        });
;(function($){
    $.fn.rating = function(callback){
        
        callback = callback || function(){};

        // each for all item
        this.each(function(i, v){
            
            $(v).data('rating', {callback:callback})
                .bind('init.rating', $.fn.rating.init)
                .bind('set.rating', $.fn.rating.set)
                .bind('hover.rating', $.fn.rating.hover)
                .trigger('init.rating');
        });
    };
    
    $.extend($.fn.rating, {
        init: function(e){
            var el = $(this),
                list = '',
                isChecked = null,
                childs = el.children(),
                i = 0,
                l = childs.length;
            
            for (; i < l; i++) {
                list = list + '<a class="star" title="' + $(childs[i]).val() + '" />';
                if ($(childs[i]).is(':checked')) {
                    isChecked = $(childs[i]).val();
                };
            };
            
            childs.hide();
            
            el
                .append('<div class="stars">' + list + '</div>')
                .trigger('set.rating', isChecked);
            
            $('a', el).bind('click', $.fn.rating.click);            
            el.trigger('hover.rating');
        },
        set: function(e, val) {
            var el = $(this),
                item = $('a', el),
                input = undefined;
            
            if (val) {
                item.removeClass('fullStar');
                
                input = item.filter(function(i){
                    if ($(this).attr('title') == val)
                        return $(this);
                    else
                        return false;
                });
                
                input
                    .addClass('fullStar')
                    .prevAll()
                    .addClass('fullStar');
            }
            
            return;
        },
        hover: function(e){
            var el = $(this),
                stars = $('a', el);
            
            stars.bind('mouseenter', function(e){
                // add tmp class when mouse enter
                $(this)
                    .addClass('tmp_fs')
                    .prevAll()
                    .addClass('tmp_fs');
                
                $(this).nextAll()
                    .addClass('tmp_es');
            });
            
            stars.bind('mouseleave', function(e){
                // remove all tmp class when mouse leave
                $(this)
                    .removeClass('tmp_fs')
                    .prevAll()
                    .removeClass('tmp_fs');
                
                $(this).nextAll()
                    .removeClass('tmp_es');
            });
        },
        click: function(e){
            e.preventDefault();
            var el = $(e.target),
                container = el.parent().parent(),
                inputs = container.children('input'),
                rate = el.attr('title');
                
            matchInput = inputs.filter(function(i){
                if ($(this).val() == rate)
                    return true;
                else
                    return false;
            });
            
            matchInput.attr('checked', true);
            
            container
                .trigger('set.rating', matchInput.val())
                .data('rating').callback(rate, e);
        }
    });
    
})(jQuery);

  </script>